### ISSUE TITLE
args.dataset = 'ft'

### ISSUE THREAD

**Issue by yitang** [phunterlau/kaggle_statefarm#2]
Hello, Thanks for providing this set of scripts. I am studying it to practise DL and learn MXNET. 

I wonder what's the use of `args.dataset` variable? The only difference this variable makes is the name of the fully connected layer.

``` python
fc1 = mx.symbol.FullyConnected(name='fc1' if dataset == 'imagenet' else 'fc1_%s' % dataset, data=flatten, num_hidden=num_classes)
```

You use the default value `ft` and I can't see what impact it would make on learning. Can I just delete this variable in this context? What's the purpose of having this argument and how it is used in a different context? 

Y

**Comment by phunterlau** [comment]
oh, the layer name is about distinguishing pretrained dataset vs new dataset, e.g. VGG uses imagenet, so the full connect layer's output should not be 10 classes as in the statefarm.

**Comment by yitang** [comment]
got it, thanks!
